package marketplace

import (
	"bytes"
	"reflect"
	"slices"
	"strings"
	"testing"
)

func TestRenderServerlessProjectionIsDeterministicAndComplete(t *testing.T) {
	overlay := *nonprofitServiceDefinition().ServerlessOverlay
	ports := nonprofitProjectionPorts()

	projection, err := RenderServerlessProjection(overlay, ports)
	if err != nil {
		t.Fatal(err)
	}
	reordered := overlay
	reordered.Overrides = append([]ServerlessOverride(nil), overlay.Overrides...)
	slices.Reverse(reordered.Overrides)
	reorderedPorts := append([]PortAssignment(nil), ports...)
	slices.Reverse(reorderedPorts)
	reorderedProjection, err := RenderServerlessProjection(reordered, reorderedPorts)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(projection, reorderedProjection) {
		t.Fatalf("reordering inputs changed projection:\nfirst: %#v\nsecond: %#v", projection, reorderedProjection)
	}
	if projection.RelativePath != "services/nonprofit-service/.switchyard.serverless.ts" {
		t.Fatalf("relative path: got %q", projection.RelativePath)
	}
	if projection.ContentSHA256 != contentSHA256(projection.Contents) {
		t.Fatal("content hash does not cover exact generated bytes")
	}
	wantFragments := []string{
		"// switchyard-owner: switchyard.marketplace.serverless.v1\n",
		"// switchyard-payload-sha256: " + projection.PayloadSHA256 + "\n\n",
		`const configuration = require("./serverless.ts")`,
		`configuration["custom"]["serverless-offline"]["host"] = "127.0.0.1"`,
		`configuration["custom"]["serverless-offline"]["httpPort"] = 4016`,
		`configuration["custom"]["serverless-offline"]["lambdaPort"] = 5016`,
		`configuration["custom"]["serverless-offline-sqs"]["endpoint"] = "http://127.0.0.1:19324"`,
		"module.exports = configuration\n",
	}
	for _, fragment := range wantFragments {
		if !bytes.Contains(projection.Contents, []byte(fragment)) {
			t.Fatalf("projection does not contain %q:\n%s", fragment, projection.Contents)
		}
	}
	if !isIntactOwnedServerlessProjection(projection.Contents) {
		t.Fatal("freshly rendered projection did not pass ownership inspection")
	}
}

func TestRenderServerlessProjectionRejectsUnsafeOrIncompleteInputs(t *testing.T) {
	valid := *nonprofitServiceDefinition().ServerlessOverlay
	tests := map[string]func() (ServerlessOverlay, []PortAssignment){
		"absolute directory": func() (ServerlessOverlay, []PortAssignment) {
			overlay := valid
			overlay.Directory = "/tmp"
			return overlay, nonprofitProjectionPorts()
		},
		"escaping directory": func() (ServerlessOverlay, []PortAssignment) {
			overlay := valid
			overlay.Directory = "../service"
			return overlay, nonprofitProjectionPorts()
		},
		"source replacement": func() (ServerlessOverlay, []PortAssignment) {
			overlay := valid
			overlay.Filename = overlay.SourceConfig
			return overlay, nonprofitProjectionPorts()
		},
		"missing assignment": func() (ServerlessOverlay, []PortAssignment) {
			return valid, nonprofitProjectionPorts()[:2]
		},
		"duplicate assignment": func() (ServerlessOverlay, []PortAssignment) {
			ports := nonprofitProjectionPorts()
			return valid, append(ports, ports[0])
		},
		"external host": func() (ServerlessOverlay, []PortAssignment) {
			ports := nonprofitProjectionPorts()
			ports[2].Host = "example.com"
			return valid, ports
		},
		"duplicate configuration path": func() (ServerlessOverlay, []PortAssignment) {
			overlay := valid
			overlay.Overrides = append(append([]ServerlessOverride(nil), overlay.Overrides...), overlay.Overrides[0])
			return overlay, nonprofitProjectionPorts()
		},
		"unknown format": func() (ServerlessOverlay, []PortAssignment) {
			overlay := valid
			overlay.Overrides = append([]ServerlessOverride(nil), overlay.Overrides...)
			overlay.Overrides[0].Format = "unknown"
			return overlay, nonprofitProjectionPorts()
		},
	}
	for name, inputs := range tests {
		t.Run(name, func(t *testing.T) {
			overlay, ports := inputs()
			if _, err := RenderServerlessProjection(overlay, ports); err == nil {
				t.Fatal("expected unsafe or incomplete projection input to fail")
			}
		})
	}
}

func TestPlanServerlessProjectionApplyProtectsForeignAndModifiedFiles(t *testing.T) {
	desired := mustRenderNonprofitProjection(t, nonprofitProjectionPorts())

	create, err := PlanServerlessProjectionApply(ExistingServerlessProjection{}, desired)
	if err != nil {
		t.Fatal(err)
	}
	if create.Action != ServerlessProjectionCreate || !bytes.Equal(create.ProposedContents, desired.Contents) {
		t.Fatalf("create plan: %#v", create)
	}

	unchanged, err := PlanServerlessProjectionApply(ExistingServerlessProjection{
		Exists: true, Contents: desired.Contents,
	}, desired)
	if err != nil {
		t.Fatal(err)
	}
	if unchanged.Action != ServerlessProjectionUnchanged {
		t.Fatalf("unchanged action: got %q", unchanged.Action)
	}

	previousPorts := nonprofitProjectionPorts()
	previousPorts[0].Port = 4116
	previous := mustRenderNonprofitProjection(t, previousPorts)
	replace, err := PlanServerlessProjectionApply(ExistingServerlessProjection{
		Exists: true, Contents: previous.Contents,
	}, desired)
	if err != nil {
		t.Fatal(err)
	}
	if replace.Action != ServerlessProjectionReplace ||
		replace.ExpectedCurrentSHA256 != previous.ContentSHA256 {
		t.Fatalf("replace plan: %#v", replace)
	}

	foreign, err := PlanServerlessProjectionApply(ExistingServerlessProjection{
		Exists: true, Contents: []byte("module.exports = {}\n"),
	}, desired)
	if err != nil {
		t.Fatal(err)
	}
	if foreign.Action != ServerlessProjectionRefuse || foreign.ProposedContents != nil {
		t.Fatalf("foreign-file plan: %#v", foreign)
	}

	modifiedContents := bytes.Replace(previous.Contents, []byte("4116"), []byte("4117"), 1)
	modified, err := PlanServerlessProjectionApply(ExistingServerlessProjection{
		Exists: true, Contents: modifiedContents,
	}, desired)
	if err != nil {
		t.Fatal(err)
	}
	if modified.Action != ServerlessProjectionRefuse || modified.ProposedContents != nil {
		t.Fatalf("modified-file plan: %#v", modified)
	}
}

func TestPlanServerlessProjectionCleanupRequiresExactCreatedContent(t *testing.T) {
	expected := mustRenderNonprofitProjection(t, nonprofitProjectionPorts())

	remove, err := PlanServerlessProjectionCleanup(ExistingServerlessProjection{
		Exists: true, Contents: expected.Contents,
	}, expected)
	if err != nil {
		t.Fatal(err)
	}
	if remove.Action != ServerlessProjectionRemove || remove.ProposedContents != nil {
		t.Fatalf("remove plan: %#v", remove)
	}

	modifiedContents := append(bytes.Clone(expected.Contents), []byte("// user note\n")...)
	refuse, err := PlanServerlessProjectionCleanup(ExistingServerlessProjection{
		Exists: true, Contents: modifiedContents,
	}, expected)
	if err != nil {
		t.Fatal(err)
	}
	if refuse.Action != ServerlessProjectionRefuse {
		t.Fatalf("modified cleanup action: got %q", refuse.Action)
	}

	absent, err := PlanServerlessProjectionCleanup(ExistingServerlessProjection{}, expected)
	if err != nil {
		t.Fatal(err)
	}
	if absent.Action != ServerlessProjectionUnchanged {
		t.Fatalf("absent cleanup action: got %q", absent.Action)
	}
}

func TestOwnedServerlessProjectionValidationRejectsTamperedDesiredProjection(t *testing.T) {
	desired := mustRenderNonprofitProjection(t, nonprofitProjectionPorts())
	desired.Contents = append(bytes.Clone(desired.Contents), []byte("// changed\n")...)

	if _, err := PlanServerlessProjectionApply(ExistingServerlessProjection{}, desired); err == nil {
		t.Fatal("expected tampered desired projection to fail")
	}
}

func nonprofitProjectionPorts() []PortAssignment {
	return []PortAssignment{
		{RequirementID: "http", Host: "127.0.0.1", Port: 4016},
		{RequirementID: "lambda", Host: "127.0.0.1", Port: 5016},
		{RequirementID: "elasticmq-rest", Host: "127.0.0.1", Port: 19324},
	}
}

func mustRenderNonprofitProjection(t *testing.T, ports []PortAssignment) OwnedServerlessProjection {
	t.Helper()
	projection, err := RenderServerlessProjection(*nonprofitServiceDefinition().ServerlessOverlay, ports)
	if err != nil {
		t.Fatal(err)
	}
	if strings.TrimSpace(string(projection.Contents)) == "" {
		t.Fatal("rendered projection is empty")
	}
	return projection
}
